name: "lint"

on: [push]

jobs:
  check-license:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Check Apache 2.0 license presence in source files
        run: bash scripts/check-license.sh src

  clang-format:
    runs-on: ubuntu-22.04
    steps:
      - name: apt-get Cache
        id: cache-apt-test
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/cache-apt-test
          key: ${{ runner.os }}-apt-test

      - name: apt-get Restore Cache
        if: steps.cache-apt-test.outputs.cache-hit == 'true'
        env:
          SOURCE: ${{ runner.temp }}/cache-apt-test
        run: |
          sudo cp --force -v ${SOURCE}/*.deb /var/cache/apt/archives/

      - name: Install Dependencies
        env:
          SOURCE: ${{ runner.temp }}/cache-apt-test
        run: |
          sudo apt-get -y update
          sudo apt-get -y install clang-format
          mkdir -p ${SOURCE}
          cp --force -v /var/cache/apt/archives/*.deb ${SOURCE}/

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Check for clang-format violations
        run: (find src -type f -name '*.*pp' | xargs clang-format --dry-run -Werror)
