name: "lint"

on: [push]

jobs:
  check-license:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Check SPDX identifiers
        run: bash scripts/spdx-lint.sh src
