name: "tests"

on: [push]

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: apt-get Cache
        id: cache-apt-test
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/cache-apt-test
          key: ${{ runner.os }}-apt-test

      - name: apt-get Restore Cache
        if: steps.cache-apt-test.outputs.cache-hit == 'true'
        env:
          SOURCE: ${{ runner.temp }}/cache-apt-test
        run: |
          sudo cp --force -v ${SOURCE}/*.deb /var/cache/apt/archives/

      - name: Install Dependencies
        env:
          SOURCE: ${{ runner.temp }}/cache-apt-test
        run: |
          sudo apt-get -y update
          sudo apt-get -y install git
          sudo apt-get -y install gcc meson pkg-config gcovr lcov
          sudo apt-get -y install libboost-program-options-dev libboost-system-dev
          sudo apt-get -y install libvirt-dev
          mkdir -p ${SOURCE}
          cp --force -v /var/cache/apt/archives/*.deb ${SOURCE}/

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Configure Meson
        run: meson setup -Db_coverage=true -Ddisable_bin=true build

      - name: Build Project
        run: ninja -C build -j2

      - name: Test Project
        run: ninja -C build test

      - name: Generate Code Coverage Reports
        run: |
          cd build
          ninja coverage-text
          ninja coverage-xml
          cat meson-logs/coverage.txt

      - uses: actions/upload-artifact@v3
        with:
          name: meson-logs
          path: build/meson-logs
