name: "tests"

on: [push]

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: apt-get Cache
        id: cache-apt-test
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/cache-apt-test
          key: ${{ runner.os }}-apt-test

      - name: apt-get Restore Cache
        if: steps.cache-apt-test.outputs.cache-hit == 'true'
        env:
          SOURCE: ${{ runner.temp }}/cache-apt-test
        run: |
          sudo cp --force -v ${SOURCE}/*.deb /var/cache/apt/archives/

      - name: Install Dependencies
        env:
          SOURCE: ${{ runner.temp }}/cache-apt-test
        run: |
          sudo apt-get -y update
          sudo apt-get -y install git
          sudo apt-get -y install ccache gcc meson pkg-config gcovr lcov
          sudo apt-get -y install libboost-program-options-dev libboost-system-dev
          sudo apt-get -y install libvirt-dev
          sudo apt-get -y install libgtest-dev libgmock-dev
          sudo apt-get -y install libpugixml-dev
          sudo apt-get -y install libfmt-dev
          sudo apt-get -y install libjsoncpp-dev
          mkdir -p ${SOURCE}
          cp --force -v /var/cache/apt/archives/*.deb ${SOURCE}/

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: CCache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Configure Meson
        env:
          CC: "ccache gcc"
          CXX: "ccache g++"
        run: meson setup -Db_coverage=true -Dbinary=false build

      - name: Build Project
        run: ninja -C build -j2

      - name: Test Project
        run: ninja -C build test

      - name: Generate Code Coverage Reports
        run: |
          ninja -C build coverage-text
          ninja -C build coverage-xml
          cat build/meson-logs/coverage.txt
          cat build/meson-logs/coverage.txt | tail -n 2 \
            | grep -Pq '^TOTAL.*[0-9]+.*[0-9]+\s+?100%$'

      - uses: actions/upload-artifact@v3
        with:
          name: meson-logs
          path: build/meson-logs
